services:
  postgres:
    image: postgres:16-alpine
    container_name: products_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_api
    ports:
      - "5433:5432"
    volumes:
      - products_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d products_api"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: products_api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: products_api
      DB_SSLMODE: disable
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  products_postgres_data: